# Generated by Django 3.1.2 on 2021-10-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Photo',
        ),
    ]
