# Generated by Django 3.1.2 on 2021-10-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='name'),
        ),
    ]
