# Generated by Django 3.1.2 on 2021-10-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
