# Generated by Django 3.1.2 on 2021-10-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(blank=True, max_length=200)),
                ('skill', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(max_length=100)),
            ],
        ),
    ]
