# Generated by Django 3.1.2 on 2021-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_skills', '0004_othertechskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techskills',
            name='quantity',
        ),
        migrations.AddField(
            model_name='techskills',
            name='quality',
            field=models.CharField(choices=[('basic', 'basic'), ('lower intermediate', 'lower intermediate'), ('upper intermediate', 'upper intermediate'), ('advance', 'advance'), ('expert', 'expert')], default='basic', max_length=20),
        ),
    ]
