# Generated by Django 3.1.2 on 2021-10-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_info', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
