# Generated by Django 3.1.2 on 2021-11-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_info', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Year', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
