# Generated by Django 3.1.2 on 2021-11-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_info', '0005_language_licence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='Year',
            new_name='year',
        ),
    ]
