# Generated by Django 3.2.9 on 2021-11-13 14:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('website', models.URLField()),
                ('phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the following format: '+989123456789'.", regex='^(\\+98)?9\\d{9}$')])),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('home_title', models.CharField(max_length=200)),
                ('about_title', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, max_length=700)),
                ('main_description', models.TextField(blank=True, max_length=900)),
                ('background_image', models.ImageField(upload_to='photos')),
                ('show_image', models.ImageField(upload_to='photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
