# Generated by Django 3.1.2 on 2021-10-14 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the following format: '+989123456789'.", regex='^(\\\\+98)?9\\\\d{9}$')]),
        ),
    ]
